name: JS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Install node modules
        run: yarn && cd ./packages/react-native && yarn

      - name: yarn lint
        run: yarn lint

      - name: Build
        run: yarn build && cd ./packages/react-native && yarn build
