on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Install node modules
        run: yarn

      - name: Build
        run: yarn build

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: MontyD/package-json-updated-action
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix dist index.js Version
        if: steps.version-updated.outputs.has-updated
        run: yarn fix:dist-version

      - uses: ryand56/r2-upload-action@latest
        if: steps.version-updated.outputs.has-updated
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: dist/
          destination-dir: ./
