name: Web

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ./web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Install node modules (Root)
        run: cd ../ && yarn

      - name: Install node modules
        run: yarn

      - name: Build
        run: yarn build
